### This jupyter notebook aims to briefly walk you through the key class Structure of python Package pymatgen
### pymatgen version: Python environment: pymatgen_2022_9_21

In [1]:
import os, json, functools

from pymatgen.core import Structure

import pandas as pd
import numpy as np


### Read a cif or POSCAR using pymatgen.Structure.from_file

In [2]:
struct = Structure.from_file("test_data/mp-1999_0D_Sb2O3.cif") #This function can also read POSCAR
struct

C:\Users\tyang\.conda\envs\pymatgen_2022_9_21\lib\site-packages\pymatgen\io\cif.py:1186: UserWarning: The default value of primitive was changed from True to False in https://github.com/materialsproject/pymatgen/pull/3419. CifParser now returns the cell in the CIF file as is. If you want the primitive cell, please set primitive=True explicitly.
  warnings.warn(


Structure Summary
Lattice
    abc : 7.93430228 7.934302579999999 7.93430209
 angles : 59.99999758 59.99999635000001 60.000001360000006
 volume : 353.192293724721
      A : 6.871307083059328 0.0 3.967151577733311
      B : 2.2904353408209657 6.478330936286413 3.9671515802231956
      C : 0.0 0.0 7.93430209
    pbc : True True True
PeriodicSite: Sb0 (Sb) (5.535, 1.687, 5.951) [0.7187, 0.2604, 0.2604]
PeriodicSite: Sb1 (Sb) (6.776, 4.791, 11.74) [0.7396, 0.7396, 0.7396]
PeriodicSite: Sb2 (Sb) (6.776, 4.791, 8.1) [0.7396, 0.7396, 0.2813]
PeriodicSite: Sb3 (Sb) (5.726, 1.822, 9.918) [0.7396, 0.2813, 0.7396]
PeriodicSite: Sb4 (Sb) (2.386, 1.687, 7.769) [0.2604, 0.2604, 0.7187]
PeriodicSite: Sb5 (Sb) (3.436, 4.656, 5.951) [0.2604, 0.7187, 0.2604]
PeriodicSite: Sb6 (Sb) (2.386, 1.687, 4.133) [0.2604, 0.2604, 0.2604]
PeriodicSite: Sb7 (Sb) (3.627, 4.791, 9.918) [0.2813, 0.7396, 0.7396]
PeriodicSite: O8 (O) (6.576, 2.847, 8.446) [0.8105, 0.4395, 0.4395]
PeriodicSite: O9 (O) (4.286, 1.227, 4.479)

### save Structure instance to a cif or POSCAR file.

In [3]:
struct.to_file("test_data/mp-1999_0D_Sb2O3_saved.vasp", fmt="poscar")
struct.to_file("test_data/mp-1999_0D_Sb2O3_saved.cif", fmt="cif")

"# generated using pymatgen\ndata_Sb2O3\n_symmetry_space_group_name_H-M   'P 1'\n_cell_length_a   7.93430228\n_cell_length_b   7.93430258\n_cell_length_c   7.93430209\n_cell_angle_alpha   59.99999758\n_cell_angle_beta   59.99999635\n_cell_angle_gamma   60.00000136\n_symmetry_Int_Tables_number   1\n_chemical_formula_structural   Sb2O3\n_chemical_formula_sum   'Sb8 O12'\n_cell_volume   353.19229372\n_cell_formula_units_Z   4\nloop_\n _symmetry_equiv_pos_site_id\n _symmetry_equiv_pos_as_xyz\n  1  'x, y, z'\nloop_\n _atom_site_type_symbol\n _atom_site_label\n _atom_site_symmetry_multiplicity\n _atom_site_fract_x\n _atom_site_fract_y\n _atom_site_fract_z\n _atom_site_occupancy\n  Sb  Sb0  1  0.71868082  0.26043939  0.26043939  1.0\n  Sb  Sb1  1  0.73956061  0.73956061  0.73956061  1.0\n  Sb  Sb2  1  0.73956061  0.73956061  0.28131918  1.0\n  Sb  Sb3  1  0.73956061  0.28131918  0.73956061  1.0\n  Sb  Sb4  1  0.26043939  0.26043939  0.71868082  1.0\n  Sb  Sb5  1  0.26043939  0.71868082  0.260

## To write and read structure from a json file through python package pandas, the structure needs to convert to a dictionary

In [4]:
struct_dict = struct.as_dict()
struct_dict

{'@module': 'pymatgen.core.structure',
 '@class': 'Structure',
 'charge': 0.0,
 'lattice': {'matrix': [[6.871307083059328, 0.0, 3.967151577733311],
   [2.2904353408209657, 6.478330936286413, 3.9671515802231956],
   [0.0, 0.0, 7.93430209]],
  'pbc': (True, True, True),
  'a': 7.93430228,
  'b': 7.934302579999999,
  'c': 7.93430209,
  'alpha': 59.99999758,
  'beta': 59.99999635000001,
  'gamma': 60.000001360000006,
  'volume': 353.192293724721},
 'properties': {},
 'sites': [{'species': [{'element': 'Sb', 'occu': 1.0}],
   'abc': [0.71868082, 0.26043939, 0.26043939],
   'xyz': [5.53479619192274, 1.6872125572645624, 5.950723082935859],
   'properties': {},
   'label': 'Sb0'},
  {'species': [{'element': 'Sb', 'occu': 1.0}],
   'abc': [0.73956061, 0.73956061, 0.73956061],
   'xyz': [6.775663815667788, 4.79111837902185, 11.735795377027914],
   'properties': {},
   'label': 'Sb1'},
  {'species': [{'element': 'Sb', 'occu': 1.0}],
   'abc': [0.73956061, 0.73956061, 0.28131918],
   'xyz': [6.775

In [5]:
#read from the structure dict
struct_from_dict = Structure.from_dict(struct_dict)
type(struct_from_dict), type(struct)

(pymatgen.core.structure.Structure, pymatgen.core.structure.Structure)

### Key attributes of struct

In [6]:
print("lattice constants", struct.lattice.abc, struct.lattice.a, struct.lattice.b, struct.lattice.c)
print("lattice angles", struct.lattice.angles, struct.lattice.alpha, struct.lattice.beta, struct.lattice.gamma)

lattice constants (7.93430228, 7.934302579999999, 7.93430209) 7.93430228 7.934302579999999 7.93430209
lattice angles (59.99999758, 59.99999635000001, 60.000001360000006) 59.99999758 59.99999635000001 60.000001360000006


In [7]:
#lattice vector a, b, c are the first, second and third row of the 3x3 matrix below
struct.lattice.matrix

array([[6.87130708, 0.        , 3.96715158],
       [2.29043534, 6.47833094, 3.96715158],
       [0.        , 0.        , 7.93430209]])

In [8]:
#fractional coordinates are the atomic positions relative to the lattice vectors
struct.frac_coords

array([[0.71868082, 0.26043939, 0.26043939],
       [0.73956061, 0.73956061, 0.73956061],
       [0.73956061, 0.73956061, 0.28131918],
       [0.73956061, 0.28131918, 0.73956061],
       [0.26043939, 0.26043939, 0.71868082],
       [0.26043939, 0.71868082, 0.26043939],
       [0.26043939, 0.26043939, 0.26043939],
       [0.28131918, 0.73956061, 0.73956061],
       [0.81053398, 0.43946602, 0.43946602],
       [0.56053398, 0.18946602, 0.18946602],
       [0.43946602, 0.81053398, 0.43946602],
       [0.43946602, 0.43946602, 0.81053398],
       [0.81053398, 0.81053398, 0.43946602],
       [0.81053398, 0.43946602, 0.81053398],
       [0.56053398, 0.18946602, 0.56053398],
       [0.18946602, 0.56053398, 0.18946602],
       [0.43946602, 0.81053398, 0.81053398],
       [0.18946602, 0.18946602, 0.56053398],
       [0.56053398, 0.56053398, 0.18946602],
       [0.18946602, 0.56053398, 0.56053398]])

In [9]:
#cartesian coordinates
struct.cart_coords

array([[ 5.53479619,  1.68721256,  5.95072308],
       [ 6.77566382,  4.79111838, 11.73579538],
       [ 6.77566382,  4.79111838,  8.09996944],
       [ 5.72609145,  1.82247875,  9.91788216],
       [ 2.38607861,  1.68721256,  7.76863581],
       [ 3.43565097,  4.65585219,  5.95072308],
       [ 2.38607861,  1.68721256,  4.13280987],
       [ 3.62694623,  4.79111838,  9.91788217],
       [ 6.57599638,  2.84700631,  8.44579563],
       [ 4.28556078,  1.22742358,  4.47864432],
       [ 4.87618165,  5.25090736,  8.44579564],
       [ 4.02627448,  2.84700631,  9.91787808],
       [ 7.42590355,  5.25090736,  9.91787848],
       [ 6.57599638,  2.84700631, 11.38996092],
       [ 4.28556078,  1.22742358,  7.42280961],
       [ 2.58574604,  3.63132462,  4.47864432],
       [ 4.87618165,  5.25090736, 11.38996093],
       [ 1.73583887,  1.22742358,  5.95072677],
       [ 5.13546794,  3.63132462,  5.95072717],
       [ 2.58574604,  3.63132462,  7.42280961]])

In [10]:
#The distance matrix contains the distance between atoms. Note that the periodic boundary condition is taken into account while
#calculating the distance between atoms, that is, the smallest inter-site distance.
print(struct.distance_matrix.shape)
struct.distance_matrix

(20, 20)


array([[0.        , 3.97406247, 3.97405544, 3.97405517, 3.63582578,
        3.63582617, 3.63582602, 5.38631083, 2.94187125, 1.98469416,
        4.39988814, 4.39988811, 2.94186448, 2.9418642 , 1.98469992,
        3.8266806 , 4.39989057, 3.82668036, 1.98470017, 3.82668359],
       [3.97406247, 0.        , 3.63582594, 3.63582616, 3.97406276,
        3.97406234, 5.38632159, 3.63582602, 3.82668749, 4.39989401,
        3.82668743, 3.82668744, 1.98470136, 1.98470156, 2.94186544,
        4.39989387, 1.98470146, 4.39989424, 2.94186511, 2.9418653 ],
       [3.97405544, 3.63582594, 0.        , 3.63582592, 5.38631107,
        3.97405528, 3.97406276, 3.63582578, 1.98470012, 2.94186453,
        1.98470002, 3.82668333, 1.98469415, 3.82668039, 4.39988826,
        2.9418644 , 3.82668033, 4.39989088, 2.94187124, 4.39988817],
       [3.97405517, 3.63582616, 3.63582592, 0.        , 3.97405528,
        5.38631079, 3.97406234, 3.63582617, 1.98469995, 2.94186418,
        3.8266837 , 1.98470009, 3.82668054, 1

### How to make a supercell

In [11]:
help(struct.make_supercell)

Help on method make_supercell in module pymatgen.core.structure:

make_supercell(scaling_matrix: 'ArrayLike', to_unit_cell: 'bool' = True, in_place: 'bool' = True) -> 'Structure' method of pymatgen.core.structure.Structure instance
    Create a supercell.
    
    Args:
        scaling_matrix (ArrayLike): A scaling matrix for transforming the lattice
            vectors. Has to be all integers. Several options are possible:
    
            a. A full 3x3 scaling matrix defining the linear combination
               the old lattice vectors. E.g., [[2,1,0],[0,3,0],[0,0,
               1]] generates a new structure with lattice vectors a' =
               2a + b, b' = 3b, c' = c where a, b, and c are the lattice
               vectors of the original structure.
            b. An sequence of three scaling factors. E.g., [2, 1, 1]
               specifies that the supercell should have dimensions 2a x b x
               c.
            c. A number, which simply scales all lattice vectors by 

In [12]:
#create a 2x3x4 supercell. Remember: set in_place=False to return the supercell object, instead of overwriting the original 
#unit cell structure
sc_struct = struct.make_supercell(scaling_matrix=[2, 3, 4], in_place=False)

In [13]:
struct.lattice.abc, sc_struct.lattice.abc

((7.93430228, 7.934302579999999, 7.93430209),
 (15.86860456, 23.80290774, 31.73720836))

### About our 0D and 1D materials datasets
#### 0D materials dataset: prescreened_0D_candidates_w_tol_added.json & prescreened_0D_candidates_w_tol_added.xlsx
#### 1D materials dataset: prescreened_1D_candidates_w_tol_added.json & prescreened_1D_candidates_w_tol_added.xlsx
#### The two materials datasets are in both the json and xlsx form. The xlsx file is easy for you to take a look at the data using Microsoft Excel

In [25]:
ZeroD_df = pd.read_json("data/prescreened_0D_candidates_w_tol_added.json")
OneD_df  = pd.read_json("data/prescreened_1D_candidates_w_tol_added.json")
len(ZeroD_df), len(OneD_df)

(3458, 1091)

In [15]:
ZeroD_df.head()
#The row index is the respective materials project ID

material_id                                           task_ids  \
mp-866807    mp-866807  [mp-867096, mp-867084, mp-1378742, mp-1777925,...   
mp-703297    mp-703297  [mp-1671109, mp-1774926, mp-703297, mp-1425530...   
mp-1204069  mp-1204069               [mp-1982857, mp-1844506, mp-1204069]   
mp-569005    mp-569005  [mp-922246, mp-2754704, mp-907602, mp-921998, ...   
mp-558853    mp-558853  [mp-558853, mp-1361432, mp-730825, mp-749809, ...   

            nsites                                  database_IDs  \
mp-866807       26                                            {}   
mp-703297       28                      {'icsd': ['icsd-73623']}   
mp-1204069      98  {'icsd': ['icsd-39217'], 'pf': ['pf-35262']}   
mp-569005       30                      {'icsd': ['icsd-35139']}   
mp-558853       60                      {'icsd': ['icsd-67817']}   

            energy_above_hull           elements formula_pretty  band_gap  \
mp-866807            0.020061  [F, H, O, Ti, Zn]   TiZnH12(OF)6    3.1431   
mp-703297            0.041865       [H, N, O, S]      H7S(NO2)2    5.2916   
mp-1204069           0.047568   [H, Mg, N, O, V]    MgV5H20NO22    2.5010   
mp-569005            0.005116           [Cl, Mo]          MoCl4    0.0000   
mp-558853            0.060313      [As, C, F, N]       AsC3N3F8    3.9572   

                                                    structure  no_of_icsd_ids  \
mp-866807   {'@module': 'pymatgen.core.structure', '@class...               0   
mp-703297   {'@module': 'pymatgen.core.structure', '@class...               1   
mp-1204069  {'@module': 'pymatgen.core.structure', '@class...               1   
mp-569005   {'@module': 'pymatgen.core.structure', '@class...               1   
mp-558853   {'@module': 'pymatgen.core.structure', '@class...               1   

            ...  0D_contained_rt_liquids        0D_contained_charged_ions  \
mp-866807   ...                                                    TiF6--   
mp-703297   ...                              NH4+|NH4+|N2H6++|SO4--|SO4--   
mp-1204069  ...          H2O|H2O|H2O|H2O  Mg(H2O)6++|Mg(H2O)6++|NH4+|NH4+   
mp-569005   ...                                                             
mp-558853   ...                                                             

           0D_min_inter_clt_dis is_MP_initial_str_1D 1D_contained_rt_gases  \
mp-866807              1.894249                False                         
mp-703297              1.619409                False                         
mp-1204069             1.669548                False                         
mp-569005              3.660618                False                         
mp-558853              2.922396                False                         

            1D_contained_rt_liquids  1D_contained_charged_ions  \
mp-866807                                                        
mp-703297                                                        
mp-1204069                                                       
mp-569005                                                        
mp-558853                                                        

           1D_min_inter_clt_dis rep_tol  \
mp-866807           100000000.0    0.15   
mp-703297           100000000.0    0.10   
mp-1204069          100000000.0    0.05   
mp-569005           100000000.0    0.00   
mp-558853           100000000.0    0.20   

                                              tol_equivalents  
mp-866807   {'0.15000000000000002': ['0.15000000000000002'...  
mp-703297   {'0.1': ['0.1', '0.15000000000000002', '0.2', ...  
mp-1204069  {'0.05': ['0.05', '0.1', '0.15000000000000002'...  
mp-569005   {'0.0': ['0.0', '0.05', '0.1', '0.150000000000...  
mp-558853   {'0.0': ['0.0', '0.05', '0.1', '0.150000000000...  

[5 rows x 23 columns]

In [16]:
OneD_df.head()
#The row index is the respective materials project ID

material_id                                           task_ids  \
mp-1210388  mp-1210388   [mp-1210388, mp-1328611, mp-1238742, mp-1886536]   
mp-569707    mp-569707  [mp-671569, mp-2270420, mp-1426390, mp-2277086...   
mp-571061    mp-571061  [mp-2745468, mp-846119, mp-717118, mp-2748932,...   
mp-734071    mp-734071  [mp-834413, mp-1205456, mp-814059, mp-805305, ...   
mp-863746    mp-863746  [mp-2026235, mp-863746, mp-1838476, mp-864855,...   

            nsites               database_IDs  energy_above_hull  \
mp-1210388      72        {'pf': ['pf-2084']}           0.050451   
mp-569707       12   {'icsd': ['icsd-76649']}           0.009326   
mp-571061       64  {'icsd': ['icsd-240715']}           0.000000   
mp-734071       34                         {}           0.070435   
mp-863746        8                         {}           0.000000   

                    elements formula_pretty  band_gap  \
mp-1210388  [C, H, N, Na, O]      NaH8CN5O3    4.2591   
mp-569707       [Bi, Br, Se]         BiSeBr    1.6912   
mp-571061       [Cl, Nb, Se]     Nb3Se10Cl3    1.0269   
mp-734071     [Cr, H, Li, O]     Li2Cr2H4O9    2.6469   
mp-863746           [Br, Tb]          TbBr3    2.8564   

                                                    structure  no_of_icsd_ids  \
mp-1210388  {'@module': 'pymatgen.core.structure', '@class...               0   
mp-569707   {'@module': 'pymatgen.core.structure', '@class...               1   
mp-571061   {'@module': 'pymatgen.core.structure', '@class...               1   
mp-734071   {'@module': 'pymatgen.core.structure', '@class...               0   
mp-863746   {'@module': 'pymatgen.core.structure', '@class...               0   

            ...  0D_contained_rt_liquids  0D_contained_charged_ions  \
mp-1210388  ...                                                       
mp-569707   ...                                                       
mp-571061   ...                                                       
mp-734071   ...                                                       
mp-863746   ...                                                       

           0D_min_inter_clt_dis is_MP_initial_str_1D 1D_contained_rt_gases  \
mp-1210388          100000000.0                 True                         
mp-569707           100000000.0                 True                         
mp-571061           100000000.0                 True                         
mp-734071           100000000.0                 True                         
mp-863746           100000000.0                 True                         

            1D_contained_rt_liquids  1D_contained_charged_ions  \
mp-1210388                                                       
mp-569707                                                        
mp-571061                                                        
mp-734071                                                        
mp-863746                                                        

           1D_min_inter_clt_dis rep_tol  \
mp-1210388             1.705668    0.10   
mp-569707              3.618752    0.15   
mp-571061              3.003531    0.00   
mp-734071              1.720991    0.10   
mp-863746              4.107553    0.00   

                                              tol_equivalents  
mp-1210388  {'0.1': ['0.1', '0.15000000000000002', '0.2', ...  
mp-569707   {'0.15000000000000002': ['0.15000000000000002'...  
mp-571061   {'0.0': ['0.0', '0.05', '0.1', '0.150000000000...  
mp-734071   {'0.1': ['0.1', '0.15000000000000002', '0.2', ...  
mp-863746   {'0.0': ['0.0', '0.05', '0.1', '0.150000000000...  

[5 rows x 23 columns]

#### ZeroD_df and OneD_df have the same columns. 
#### You may use the data in the following two columns: (a) Column "structure" stores the pymatgen dictionary form of the atomic structure and (b) "rep_tol" is the selected bond tolerance for a material to tell which atoms of the structure are bound to one another.

### How did we tell the dimensionality of a given material?
#### *I have completed this. Just give you a rough idea how we did this so you can better understand what I call 0D and 1D materials and how we can figure out every constituent 0D cluster or 1D chain.*
#### step 1: Calculate the distance between any atoms under the periodic boundary condition. Let's denote L(A, B) the distance between atom A and B
#### step 2: Compare L(A, B) with the sum of the covalent radii of A and B up to a bond tolerance. The latter is denoted as [r(A)+r(B)]\*rep_tol. r(A) and r(B) are fixed values and stored in file "atomic_radius.json". There is no clear boundary between bonding and non-bonding. That's why we need to introduce a bond tolerance. I have devised a method to define a representative bond tolerance (rep_tol) for each material. If L(A, B) < [r(A)+r(B)]\*rep_tol, then atom A is bound to atom B. Otherwise, they are not bound.
#### step 3: Partition all atoms of a material into a set of atomic clusters. Within a cluster, atoms are bound to each other.
#### step 4: figure out the dimensionality of every cluster. If the atomic clusters are isolated from each other in all dimensions, the material is 0D. If the clusters are 1D chains, the material is 1D. If the atomic clusters are slabs/sheets, the material is 2D.

#### For the initial structures of these 0D and 1D materials, I have prepared a VESTA file each. In these VESTE files, the bond length thresholds have been adjusted based on their respective rep_tol. So by dragging and dropping those VESTA files into VESTA, you will readily figure out what atoms constitute a 0D cluster or 1D chain.

In [17]:
#Read a structure from the above pandas dataframe
struct = Structure.from_dict(ZeroD_df.loc["mp-1999", "structure"])
struct

Structure Summary
Lattice
    abc : 7.934302282144142 7.934302580570291 7.93430209
 angles : 59.9999975754691 59.99999635121014 60.00000136319022
 volume : 353.1922938452046
      A : 6.87130709 0.0 3.96715157
      B : 2.29043535 6.47833094 3.96715157
      C : 1e-08 1e-08 7.93430209
    pbc : True True True
PeriodicSite: Sb (5.535, 1.687, 5.951) [0.7187, 0.2604, 0.2604]
PeriodicSite: Sb (6.776, 4.791, 11.74) [0.7396, 0.7396, 0.7396]
PeriodicSite: Sb (6.776, 4.791, 8.1) [0.7396, 0.7396, 0.2813]
PeriodicSite: Sb (5.726, 1.822, 9.918) [0.7396, 0.2813, 0.7396]
PeriodicSite: Sb (2.386, 1.687, 7.769) [0.2604, 0.2604, 0.7187]
PeriodicSite: Sb (3.436, 4.656, 5.951) [0.2604, 0.7187, 0.2604]
PeriodicSite: Sb (2.386, 1.687, 4.133) [0.2604, 0.2604, 0.2604]
PeriodicSite: Sb (3.627, 4.791, 9.918) [0.2813, 0.7396, 0.7396]
PeriodicSite: O (6.576, 2.847, 8.446) [0.8105, 0.4395, 0.4395]
PeriodicSite: O (4.286, 1.227, 4.479) [0.5605, 0.1895, 0.1895]
PeriodicSite: O (4.876, 5.251, 8.446) [0.4395, 0.8105

In [19]:
with open('data//atomic_radius.json','r') as f:
    atomic_radius = json.load(f)
    
#is_bonded_matrix_I is the function that I used to determine bonding situation
def is_bonded_matrix_I(distance_matrix, species_list, tol):
    bonded_matrix = np.full(distance_matrix.shape, False, dtype=bool)
    for site1_ind in range(distance_matrix.shape[0]):
        for site2_ind in range(site1_ind, distance_matrix.shape[0]):
            sp1 = species_list[site1_ind]
            sp2 = species_list[site2_ind]
            dist = distance_matrix[site1_ind, site2_ind]
            if sp1 in atomic_radius and sp2 in atomic_radius:
                bond_length = atomic_radius[sp1] + atomic_radius[sp2]
                if dist < (1 + tol) * bond_length:
                    bonded_matrix[site1_ind, site2_ind] = True
                    bonded_matrix[site2_ind, site1_ind] = True
                else:
                    bonded_matrix[site1_ind, site2_ind] = False
                    bonded_matrix[site2_ind, site1_ind] = False
            else:
                raise ValueError("No bond data for elements {} - {}".format(sorted([sp1, sp2])))
    return bonded_matrix

#I just came up with is_bonded_matrix_II while preparing this tutorial. It does the same work as is_bonded_matrix_I 
#but should be faster. Not sure if there are bugs. Please help to check.
def is_bonded_matrix_II(distance_matrix, species_list, tol):
    atom_2_radius_arr = [atomic_radius[spec] for spec in species_list]
    atom_2_radius_arr = np.array([atom_2_radius_arr] * distance_matrix.shape[0])
    ref_covalent_radii_arr = (atom_2_radius_arr + atom_2_radius_arr.transpose()) * (tol + 1)
    
    bonded_matrix = np.full(distance_matrix.shape, False, dtype=bool)
    bonded_matrix[distance_matrix < ref_covalent_radii_arr] = True
    return bonded_matrix


def cal_logical_or(boolean_matrix):
    return functools.reduce(lambda arr_1, arr_2: np.logical_or(arr_1, arr_2), boolean_matrix)

#This function is a bit hard to understand. But the function name well tells what it does. The output is the set of indice of the atoms
#which are bound to site1
def find_bonded_sites_of_a_site(site1_ind, bonded_matrix, ind_arr):
    site2_ind_set = set(ind_arr[bonded_matrix[site1_ind]])
    boolean_site2_ind_arr = cal_logical_or(bonded_matrix[list(site2_ind_set)])
    while True:
        site2_ind_set_I = set(ind_arr[boolean_site2_ind_arr])
        diff_site2_ind_set = site2_ind_set_I.difference(site2_ind_set)
        if diff_site2_ind_set:
            site2_ind_set = site2_ind_set_I
            new_boolean_site2_ind_arr = cal_logical_or(bonded_matrix[list(diff_site2_ind_set)])
            boolean_site2_ind_arr = np.logical_or(boolean_site2_ind_arr, new_boolean_site2_ind_arr)
        else:
            break
    
    return site2_ind_set

#The wrapped-up function to take care of the whole clustering process. 
#The output is a dictionary: value=a list of 0-based indice of the atoms within a cluster; key=the smallest 0-based atomic index of that cluster
def clusterfy(structure,tol):
    distance_matrix = structure.distance_matrix
    bonded_matrix_I = is_bonded_matrix_I(distance_matrix, [str(spec) for spec in structure.species], tol)
    bonded_matrix_II = is_bonded_matrix_II(distance_matrix, [str(spec) for spec in structure.species], tol)
    assert np.alltrue(bonded_matrix_I==bonded_matrix_II), "function is_bonded_matrix_I and bonded_matrix_II output different bonded_matrix for structure {}".format(structure)
    bonded_matrix = bonded_matrix_I
    
    clusters = {}
    ind_arr = np.array(range(len(structure)))
    counted_ind_list = []
    
    for site1_ind in range(len(structure)):
        if site1_ind in counted_ind_list: continue
        site2_ind_set = find_bonded_sites_of_a_site(site1_ind=site1_ind, bonded_matrix=bonded_matrix, ind_arr=ind_arr)
        clusters[min(site2_ind_set)] = list(sorted(site2_ind_set))
        counted_ind_list.extend(list(site2_ind_set))
    sorted_counted_ind_list = sorted(counted_ind_list)
    
    assert sorted_counted_ind_list == sorted(ind_arr), "Some sites are missing\n Counted sites {}; total list {}".format(sorted_counted_ind_list, ind_arr)
    clusters = {int(min_site_ind):[int(all_site_ind) for all_site_ind in site_ind_list] for min_site_ind, site_ind_list in clusters.items()}
    return clusters

#### In what follows, I will show you how to obtain the 0-based indice of the atoms within a cluster

In [20]:
mp_id = "mp-24113"
proxy_df = ZeroD_df

#retrieve the structure from the dataframe
struct = Structure.from_dict(proxy_df.loc[mp_id, "structure"])

#retrieve the corresponding bond tolerance rep_tol from the dataframe
rep_tol = proxy_df.loc[mp_id, "rep_tol"]
print("rep_tol: {}".format(rep_tol))

rep_tol: 0.05


In [21]:
#You can just call this function to do everything for you.
clusters = clusterfy(structure=struct, tol=rep_tol)
clusters
#In this case, given a bond tolerance of 0.05, the structure is partitioned into 3 clusters. The smallest 0-based atomic index
#is 0, 1 and 2, respectively. The value contains all atomic indice within a cluster, inclusive of the smallest atomic index in that cluster

C:\Users\tyang\AppData\Local\Temp\ipykernel_14480\609604409.py:2: DeprecationWarning: `alltrue` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `all` instead.
  clusters = clusterfy(structure=struct, tol=rep_tol)


{0: [0, 11, 12, 13, 14, 15, 16], 1: [1, 3, 4, 5, 9], 2: [2, 6, 7, 8, 10]}

In [50]:
#Now you can use these grouped atomic indice to retrieve the corresponding atomic coordinates
struct.frac_coords[clusters[0], :]

array([[0.      , 0.      , 0.      ],
       [0.304971, 0.152485, 0.767268],
       [0.847515, 0.152485, 0.767268],
       [0.847515, 0.695029, 0.767268],
       [0.152485, 0.847515, 0.232732],
       [0.695029, 0.847515, 0.232732],
       [0.152485, 0.304971, 0.232732]])

In [51]:
struct.cart_coords[clusters[2], :]

array([[ 3.143218  , -1.81474163,  0.74173954],
       [ 3.143218  , -2.78017499,  2.14213779],
       [ 2.30712516, -1.33201951,  2.14213779],
       [ 3.97931084, -1.33201951,  2.14213779],
       [ 3.143218  , -1.81474163,  1.7674584 ]])

In [24]:
#Save the whole structure and every cluster, separately, so that you can use VESTA to visualize
struct.to_file("test_data/{}_entire.cif".format(mp_id), fmt="cif")

for smallest_ind in clusters.keys():
    sub_struct = Structure(lattice=struct.lattice.matrix, 
                           species=[struct.species[atom_ind] for atom_ind in clusters[smallest_ind]], 
                           coords=struct.frac_coords[clusters[smallest_ind]], 
                           coords_are_cartesian=False)
    sub_struct.to_file("test_data/{}_cluster_{}.cif".format(mp_id, smallest_ind), fmt="cif")